# Generated by Django 4.2.1 on 2023-06-08 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_reg_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='reg',
            name='pwd',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
