# Generated by Django 4.2.1 on 2023-06-08 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_reg_email_alter_reg_pwd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg',
            name='image',
            field=models.ImageField(upload_to='pictures'),
        ),
    ]
