# Generated by Django 4.2.1 on 2023-06-08 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_reg_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg',
            name='image',
            field=models.ImageField(upload_to='pict'),
        ),
    ]
