# Generated by Django 4.2.1 on 2023-06-10 05:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_reg_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reg',
            old_name='username',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='reg',
            name='email',
        ),
        migrations.RemoveField(
            model_name='reg',
            name='pwd',
        ),
        migrations.AddField(
            model_name='reg',
            name='des',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
